version: "3.9"

services:
  client:
    container_name: client
    build:
      context: ./client/
      dockerfile: ../Dockerfile.dev 
    ports:
      - 3000:3000

  posts:
    container_name: posts
    build:
      context: ./posts/
      dockerfile: ../Dockerfile.dev 
    ports:
      - 4000:4000

  comments:
    container_name: comments
    build:
      context: ./comments/
      dockerfile: ../Dockerfile.dev 
    ports:
      - 4001:4001

  query:
    container_name: query
    build:
      context: ./query/
      dockerfile: ../Dockerfile.dev 
    ports:
      - 4002:4002

  moderation:
    container_name: moderation
    build:
      context: ./moderation/
      dockerfile: ../Dockerfile.dev 
    ports:
      - 4003:4003

  event-bus:
    container_name: event-bus
    build:
      context: ./event-bus/
      dockerfile: ../Dockerfile.dev 
    ports:
      - 4005:4005

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - client
      - posts
      - comments
      - query
      - moderation
      - event-bus
